name: Publish Github Page

on:
    push:
        branches: ["main"]

jobs:
    publish_page:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Github User
              run: |
                  git config --global user.email "actions@users.noreply.github.com"
                  git config --global user.name 'Sachin Acharya'
                  git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20"

            - name: Installing Dependencies
              run: npm install

            - name: Getting the latest commit message
              id: commit_msg
              run: echo "::set-output name=message::$(git log -1 --pretty=%B)"

            - name: Publish Page
              run: npm run deploy -- -m "${{ steps.commit_msg.outputs.message }}"
              shell: bash
